FE = float(input("ENTER SCORE Foundation English : "))
GB = float(input("ENTER SCORE General Business : "))
ICS = float(input("ENTER SCORE Introduction to Computer Systems : "))
CP = float(input("ENTER SCORE Computer Programming : "))
print("--- Your Score ---")
print("Foundation English : ",FE)
print("General Business : ",GB)
print("Introduction to Computer Systems : ",ICS)
print("Computer Programming : ",CP)